name: Release Docker
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and publish to Dockerhub
      run: |
        export TAG=$(echo ${GITHUB_REF} | cut -d'/' -f3)
        export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
        export DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
        make release
